import Head from 'next/head';
import Link from 'next/link';
import { useUser } from '@auth0/nextjs-auth0';

export default function Home() {
  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;

  if (error) return <div>{error.message}</div>;

  const SendUserToDBController = (user) => {
    fetch('/api/controllers/CheckUser', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(user),
    }).catch((err) => {
      console.log('Server Error: ', err);
    });
  };

  return (
    <div>
      <Head>
        <title>WAHOOT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          WELCOME TO WAHOOT! <br />
          LET'S PLAY!
        </h1>

        <button>
          <Link href="/play">PLAY</Link>
        </button>
        {user ? (
          <div>
            <p>{JSON.stringify(user)}</p>
            {SendUserToDBController(user)}
            <button>
              <Link href="/api/auth/logout">LOGOUT</Link>
            </button>
          </div>
        ) : (
          <button>
            <Link href="/api/auth/login">LOGIN/REGISTER</Link>
          </button>
        )}
      </main>
    </div>
  );
}
