import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { WelcomeText } from "../components/WelcomeText";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>WAHOOT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          WELCOME TO WAHOOT! <br />
          LET'S PLAY!
        </h1>

        <botton>
          <Link href="/play">PLAY</Link>
        </botton>
        <botton>
          <Link href="/auth">LOGIN/REGISTER</Link>
        </botton>
      </main>
    </div>
  );
}
